jwt:
  secretKey: meatTeam

version: /api/v2

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: discord
    password: 1234
    url: jdbc:mariadb://localhost:3307/discord

  mail:
    # mail default settings
    default-encoding: UTF-8
    # mail custom settings
    host: smtp.gmail.com
    port: 587
    username: wodus331@gmail.com
    password: abgrxabwbjkyefef
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        mime:
          charset: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#logging:
#  level:
#    org.springframework: DEBUG